name: Build & Deploy Angular to cPanel

# Trigger on pushes to main, or manual dispatch
on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  # Combined build and deploy job
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Cache npm modules
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Build (production)
        run: npx ng build --configuration=production

      # Deploy directly without creating an artifact
      - name: Deploy to cPanel via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.CPANEL_HOST }}
          username: ${{ secrets.CPANEL_USERNAME }}
          password: ${{ secrets.CPANEL_PASSWORD }}
          protocol: ftp
          port: 21
          local-dir: ./dist/menuapp/browser/ # Path to your Angular build output
